version: '3.8'
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
    - 8000:8000
  image: app:django
  container_name: django_container
  command: python manage.py runserver 0.0.0.0:8000
  # Restart policy
  restart: unless-stopped
  depends_on:
    - db
 db:
  image: mysql:8.0.31
  ports:
   - "3307:3007"
  environment:
   MYSQL_DATABASE: 'smartcare_surgery'
   MYSQL_ROOT_PASSWORD: 'Alpha101-'
  volumes:
   - ./data/mysql/db:/var/lib/mysql
  # Restart policy
  restart: always

